# Generated by Django 2.2.4 on 2020-08-27 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Attribute')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('product_description', models.TextField()),
                ('product_code', models.SlugField(editable=False, max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_negotiable', models.BooleanField(default=True)),
                ('condition', models.CharField(choices=[('brand-new', 'Brand New'), ('like-new', 'Like New'), ('excellent', 'Excellent'), ('fair', 'Fair'), ('not-working', 'Not Working')], max_length=50)),
                ('days_to_run', models.IntegerField()),
                ('allow_variants', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='products')),
                ('anchal', models.CharField(max_length=100)),
                ('lot_no', models.IntegerField()),
                ('engine', models.CharField(max_length=100)),
                ('make_year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('Kilometers', models.IntegerField()),
                ('transmission', models.CharField(choices=[('manual-2d', 'Manual 2D'), ('manual-4d', 'Manual 4D'), ('auto-2d', 'Auto 2D'), ('auto-4d', 'Auto 4D')], max_length=50)),
                ('views', models.IntegerField()),
                ('home_delivery', models.BooleanField(default=True)),
                ('delivery_charge', models.IntegerField()),
                ('delivery_area', models.CharField(max_length=100)),
                ('warranty_type', models.CharField(choices=[('dealer', 'Dealer/shop'), ('importer', 'Manufacturer/Importer'), ('none', 'No warranty')], max_length=50)),
                ('warranty_period', models.CharField(max_length=100)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='Category')),
                ('product_attributes', models.ManyToManyField(to='business.Attribute')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('product_name',),
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=120)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.AttributeVariant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Product')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='Category')),
            ],
        ),
    ]
