# Generated by Django 2.2.4 on 2020-08-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevariant',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='allow_variants',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_attributes',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='AttributeVariant',
        ),
        migrations.DeleteModel(
            name='ProductAttributeValue',
        ),
    ]
