# Generated by Django 2.2.4 on 2020-08-27 06:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20200827_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dealer', 'Dealer/shop'), ('importer', 'Manufacturer/Importer'), ('none', 'No warranty')], default=False, max_length=20),
        ),
    ]
