# Generated by Django 2.2.4 on 2020-08-27 07:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_product_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='feature',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NULL', 'none')], default=False, max_length=4),
        ),
    ]
