# Generated by Django 2.2.4 on 2020-08-27 07:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20200827_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='feature',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NULL', 'none'), ('importer', 'Manufacturer/Importer'), ('none', 'No warranty')], default=False, max_length=18),
        ),
    ]
